name: Build README

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 */2 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"
      - name: Install Python dependencies
        run: |
          python -m pip install -r requirements.txt
      - name: Update README
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |-
          python build_readme.py
      - name: Commit and push if changed
        run: |-
          git config --global user.name "README-bot"
          git config --global user.email "actions@users.noreply.github.com"
          # Pull the latest changes from the remote branch
          git pull --rebase
          git add README.md
          git commit -m "Updated README content" || exit 0
          git push
